### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by isidroas**
Failing since 67624eba0b09 (#2043)
with the following error:

```python
Traceback (most recent call last):
  File "/tmp/rq/examples/run_example.py", line 6, in <module>
    from rq import Connection, Queue
ImportError: cannot import name 'Connection' from 'rq' (/tmp/rq/rq/__init__.py). Did you mean: 'connections'?
```

### CODE REVIEW

**Comment by selwin** [comment]
Thanks!
