### ISSUE TITLE
[CRITICAL] Simple Python Functions with no return value in RQ 1.0 trigger AttributeError

### ISSUE THREAD

**Issue by teward** [rq/rq#1120]
Hello.

I am testing a simple function which writes to a file with an RQ task on a Redis server.  This is defined in `localdependencies.py` in the same working directory as `rq` as follows:

```
import datetime


def writedate(path='/tmp/redis-writedate.txt'):
    dt = datetime.datetime.now().isoformat().encode('utf-8')
    print(dt.decode('utf-8'))
    with open(path, mode="wb") as f:
        f.write(dt + b'\n')
```

I have been manually en-queuing this with `queuer.py` called via `python3` in the same working dir:

```
from redis import Redis
from rq import Queue
from time import sleep
import rutil

if __name__ == "__main__":
    redis_conn = Redis(host='10.73.252.30')
    q = Queue('testing', connection=redis_conn)
    job = q.enqueue(rutil.writedate(), args=[])
```

The worker with `rq worker` or a custom worker handler ***ALWAYS*** returns an error:

```AttributeError: 'NoneType' object has no attribute '__module__'```

Am I utilizing this incorrectly?  Because this used to work in older RQ versions such as 0.13.0, but in 1.0 this simply "dies hard" in this manner... if this is how RQ is going to handle functions which don't return anything, then RQ has become a broken unusable piece of software.

---

Similarly, if I return a String of the isoformat of the date in a function, I get an error such as this:

```ModuleNotFoundError: No module named '2019-07-24T12:45:58'```

**Comment by teward** [comment]
...nevermind I am an idiot.  Didn't notice the () for the function call...
