### ISSUE TITLE
TypeError: dependencies_are_met() got an unexpected keyword argument 'exclude_job_id'

### ISSUE THREAD

**Issue by jtfidje** [rq/rq#1689]
After upgrade from 1.10.1 -> 1.11.0 I get the error message in the title. Was this a planned change?

**Comment by selwin** [comment]
We had to make some changes to accommodate the new `Dependency`. `dependencies_are_met` now accept `parent_job` instead of `exclude_job_id`.  https://github.com/rq/rq/blob/9db728921d92b3edc8107154e07362b3ed7a8e24/rq/job.py#L985
